### PR TITLE
Fix inconsistent trailing slash in remappings

### LINKED ISSUE #47: Inconsistent tailing slash in remapping name and path
Hi, I notice that when formatting remappings in the compiler settings, a slash `/` is pushed if the remapped path does not end with `/`.
https://github.com/foundry-rs/compilers/blob/6528e4ac0b8f17599fd4b6b1e091b21c690ad142/src/remappings.rs#L160-L162

This may lead to incorrect path remapping and cause compiler failure. 
For example, if the original remapping is `@0x/contracts-utils=/home/cluracan/code/0x-monorepo/node_modules/@0x/contracts-utils`, and one more `/` is added at the end. 
The remapping now becomes: `@0x/contracts-utils=/home/cluracan/code/0x-monorepo/node_modules/@0x/contracts-utils/`.

If the contract has one import like this: `import "@0x/contracts-utils/contracts/src/v06/LibBytesV06.sol";`
The imported path after remapping is `/home/cluracan/code/0x-monorepo/node_modules/@0x/contracts-utils//contracts/src/v06/LibBytesV06.sol`. 
Note that there is one redundant `/` in the remapped path and this leads to `File not found errors` in the compiler. 

I encounter this issue when trying to compile mainnet contract `0xDef1C0ded9bec7F1a1670819833240f027b25EfF` with the source code provided by Etherscan API.

### PR DESCRIPTION
**Pull request by Troublor**
Fix #47. One corresponding test is added. 

## Fix strategy
- Remove the code that blindly add trailing `/` when serializing `Remapping` and `RelativeRemapping`.
- Preserve the trailing `/` in the `strip_prefix` method of `Remapping`.

## Rationale
There are roughly two sources where `Remapping` comes from:
- Generated in `find_many` function.
- Loaded from configuration like `foundry.toml`.

When generating `Remapping` in `find_many` function, the algorithm makes sure that the `name` and `path` of every remapping are valid folders in the file system. Then, trailing `/`s are added to both `name` and `path` in the `impl From<RelativeRemapping> for Remapping` implementation.
https://github.com/Troublor/compilers/blob/93c5f46a7dd0c0d387dd94c8ea756812e2907d92/src/remappings.rs#L360-L365

When loading `Remapping` from user-provided configurations, the `name` and `path` of remappings should be set as it is, and do not add any trailing `/`s. 

Either way, the field `name` and `path` of `Remapping` contains intended values and should not be changed in the serialization (the implementation for `Display` trait).

PS: About coding style, I tried to use `TempProject` to write the test case but it seems the `project.compile()` method **does not respect** the `remapping` I give it via `project.with_settings(settings_with_remapping)`. The remapping just does not take effect in the compilation. Not sure whether it's I don't know how to use it or `TempProject` has some bugs.

### CODE REVIEW

**Comment by BlazeWasHere** [comment]
gm @Troublor are you still working on this?

**Comment by Troublor** [comment]
@BlazeWasHere Yeah you remind me. I will finish it this weekend.

**Review by mattsse — COMMENTED** [review]
sorry forgot about this,

could you please open a foundry pr that patches the foundry-compilers crate to this branch to check if this causes any issues

**Comment by BlazeWasHere** [comment]
ah im not approved for github workflow actions, but locally it doesnt seem to build not sure its because of my system (new pc -- have never used rust on this before) or rust crate incompatibility 

<details>
<summary>build</summary>

```sh
~> cargo check --all 
    Updating git repository `https://github.com/Troublor/compilers/`
    Updating crates.io index
    Checking foundry-config v0.2.0 (/Users/x/Code/Git/foundry/crates/config)
    Checking foundry-linking v0.2.0 (/Users/x/Code/Git/foundry/crates/linking)
error[E0308]: mismatched types
   --> crates/linking/src/lib.rs:172:36
    |
172 |         Ok(LinkOutput { libraries, libs_to_deploy })
    |                                    ^^^^^^^^^^^^^^ expected `alloy_primitives::Bytes`, found `alloy_primitives::bytes_::Bytes`
    |
    = note: `alloy_primitives::bytes_::Bytes` and `alloy_primitives::Bytes` have similar names, but are actually distinct types
note: `alloy_primitives::bytes_::Bytes` is defined in crate `alloy_primitives`
   --> /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-primitives-0.6.4/src/bytes/mod.rs:21:1
    |
21  | pub struct Bytes(pub bytes::Bytes);
    | ^^^^^^^^^^^^^^^^
note: `alloy_primitives::Bytes` is defined in crate `alloy_primitives`
   --> /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-primitives-0.7.0/src/bytes/mod.rs:21:1
    |
21  | pub struct Bytes(pub bytes::Bytes);
    | ^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `alloy_primitives` are being used?

error[E0308]: mismatched types
   --> crates/linking/src/lib.rs:187:74
    |
187 |                     bytecode.to_mut().link(file.to_string_lossy(), name, address);
    |                                       ----                               ^^^^^^^ expected `alloy_primitives::bits::address::Address`, found `Address`
    |                                       |
    |                                       arguments to this method are incorrect
    |
    = note: `Address` and `alloy_primitives::bits::address::Address` have similar names, but are actually distinct types
note: `Address` is defined in crate `alloy_primitives`
   --> /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-primitives-0.7.0/src/bits/address.rs:45:1
    |
45  | / wrap_fixed_bytes!(
46  | |     // we implement Display with the checksum, so we don't derive it
47  | |     extra_derives: [],
48  | |     /// An Ethereum address, 20 bytes in length.
...   |
86  | |     pub struct Address<20>;
87  | | );
    | |_^
note: `alloy_primitives::bits::address::Address` is defined in crate `alloy_primitives`
   --> /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-primitives-0.6.4/src/bits/address.rs:45:1
    |
45  | / wrap_fixed_bytes!(
46  | |     // we implement Display with the checksum, so we don't derive it
47  | |     extra_derives: [],
48  | |     /// An Ethereum address, 20 bytes in length.
...   |
86  | |     pub struct Address<20>;
87  | | );
    | |_^
    = note: perhaps two different versions of crate `alloy_primitives` are being used?
note: method defined here
   --> /Users/x/.cargo/git/checkouts/compilers-aa3db5570c579c95/93c5f46/src/artifacts/bytecode.rs:68:12
    |
68  |     pub fn link(
    |            ^^^^
    = note: this error originates in the macro `wrap_fixed_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> crates/linking/src/lib.rs:192:74
    |
192 |                     deployed_bytecode.link(file.to_string_lossy(), name, address);
    |                                       ----                               ^^^^^^^ expected `alloy_primitives::bits::address::Address`, found `Address`
    |                                       |
    |                                       arguments to this method are incorrect
    |
    = note: `Address` and `alloy_primitives::bits::address::Address` have similar names, but are actually distinct types
note: `Address` is defined in crate `alloy_primitives`
   --> /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-primitives-0.7.0/src/bits/address.rs:45:1
    |
45  | / wrap_fixed_bytes!(
46  | |     // we implement Display with the checksum, so we don't derive it
47  | |     extra_derives: [],
48  | |     /// An Ethereum address, 20 bytes in length.
...   |
86  | |     pub struct Address<20>;
87  | | );
    | |_^
note: `alloy_primitives::bits::address::Address` is defined in crate `alloy_primitives`
   --> /Users/x/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-primitives-0.6.4/src/bits/address.rs:45:1
    |
45  | / wrap_fixed_bytes!(
46  | |     // we implement Display with the checksum, so we don't derive it
47  | |     extra_derives: [],
48  | |     /// An Ethereum address, 20 bytes in length.
...   |
86  | |     pub struct Address<20>;
87  | | );
    | |_^
    = note: perhaps two different versions of crate `alloy_primitives` are being used?
note: method defined here
   --> /Users/x/.cargo/git/checkouts/compilers-aa3db5570c579c95/93c5f46/src/artifacts/bytecode.rs:68:12
    |
68  |     pub fn link(
    |            ^^^^
    = note: this error originates in the macro `wrap_fixed_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `foundry-linking` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
```
</details>

**Comment by Troublor** [comment]
The test cases of foundry-rs/compilers (in the CI) seem to indicate there are some problems with Windows. I don't have a Windows machine. Could someone offer some help to look into the issues?

File: src/remappings.rs [hunk 1]
```diff
@@ -67,8 +67,14 @@ impl Remapping {
 
     /// Removes the `base` path from the remapping
     pub fn strip_prefix(&mut self, base: impl AsRef<Path>) -> &mut Self {
+        // converting a string path to Path and back will lose the trailing slash,
+        // so we need to remember if the path had a trailing slash.
+        let has_trailing_slash = self.path.ends_with('/');
```
Comment (BlazeWasHere) [inline src/remappings.rs:72]: i think on windows this will be `\` instead of `/`

Comment (Troublor) [reply src/remappings.rs:84]: Thanks for your review. I realize the problem is not here. Here all the slashes in the path has already been converted to `/` even for windows. The issue is actually when converting `\` to `/`, the trailing `/` is discarded and we should preserve them. I have patched this with a new commit.

File: src/remappings.rs [hunk 2]
```diff
@@ -12,6 +12,18 @@ const DAPPTOOLS_LIB_DIR: &str = "lib";
 const JS_CONTRACTS_DIR: &str = "contracts";
 const JS_LIB_DIR: &str = "node_modules";
 
+/// Convert all `\\` to `/` in a string path on Windows.
+#[cfg(target_os = "windows")]
+fn to_slash_path_preserve_trailing_slash(path: &str) -> String {
+    use path_slash::PathExt;
+    let has_trailing_path = path.ends_with('/') || path.ends_with('\\');
```
Comment (DaniPopes) [inline src/remappings.rs:19]:
```suggestion
    let has_trailing_slash = path.ends_with('/') || path.ends_with('\\');
```

File: src/remappings.rs [hunk 3]
```diff
@@ -12,6 +12,18 @@ const DAPPTOOLS_LIB_DIR: &str = "lib";
...
+    let mut p = Path::new(path).to_slash_lossy().to_string();
```
Comment (DaniPopes) [inline src/remappings.rs:20]:
```suggestion
    let mut p = Path::new(path).to_slash_lossy().into_string();
```

File: src/remappings.rs [hunk 4]
```diff
@@ -12,6 +12,18 @@ const DAPPTOOLS_LIB_DIR: &str = "lib";
...
+    if has_trailing_path {
```
Comment (DaniPopes) [inline src/remappings.rs:21]:
```suggestion
    if has_trailing_slash {
```

File: src/remappings.rs [hunk 5]
```diff
@@ -12,6 +12,18 @@ const DAPPTOOLS_LIB_DIR: &str = "lib";
 const JS_CONTRACTS_DIR: &str = "contracts";
 const JS_LIB_DIR: &str = "node_modules";
 
+/// Convert all `\\` to `/` in a string path on Windows.
+#[cfg(target_os = "windows")]
+fn to_slash_path_preserve_trailing_slash(path: &str) -> String {
+    use path_slash::PathExt;
+    let has_trailing_slash = path.ends_with('/') || path.ends_with('\\');
+    let mut p = Path::new(path).to_slash_lossy().into_string();
```
Comment (BlazeWasHere) [inline src/remappings.rs:20]: reverting the change fixes for windows

```suggestion
    let mut p = Path::new(path).to_slash_lossy().to_string();
```

Comment (DaniPopes) [reply src/remappings.rs:20]: Oh my bad, I typod that. It's into_owned

**Review by DaniPopes — APPROVED** [review]
lgtm, pending @mattsse

**Review by mattsse — APPROVED** [review]
lgtm,

really sorry about the delay

**Comment by mattsse** [comment]
hmm this results in a bunch of failing tests

https://github.com/foundry-rs/foundry/pull/7623

can't proceed with this until sorted out

**Comment by BlazeWasHere** [comment]
> hmm this results in a bunch of failing tests
> 
> [foundry-rs/foundry#7623](https://github.com/foundry-rs/foundry/pull/7623)
> 
> can't proceed with this until sorted out

i havent updated my fork yet, can you retrigger ci again now

**Comment by klkvr** [comment]
hey @Troublor do you have plans for finishing this?

considering that CI fails I am thinking that perhaps we should take a different approach? currently in remappings.txt of a foundry project you can specify remappings in any format: any of `project=src`, `project=src/`, `project/=src`, etc would get updated to `project/=src/` because it's the way conversion `RelativeRemapping -> Remapping` works: 
https://github.com/foundry-rs/compilers/blob/a21275dc8df3514e8b076841a748cecbad60aac2/crates/artifacts/solc/src/remappings.rs#L360-L365

however, when working with i.e. etherscan projects or any sources of remappings requiring deserialization directly into `Remappings` we don't go through that conversion and validation and `name` and `path` are kept as-is.

Thus, I think we can either just update `Display` impl for `Remapping` to also push `/` to `name` if it's not present (currently we are only pushing it to `path`): https://github.com/foundry-rs/compilers/blob/a21275dc8df3514e8b076841a748cecbad60aac2/crates/artifacts/solc/src/remappings.rs#L159-L161

Also, we can consider adding this additional logic to `serde::Serialize` impl which should also work

**Comment by Troublor** [comment]
@klkvr Thanks. I restructured the patch.

**Comment by Troublor** [comment]
@klkvr I fixed some regression test oracles. Please trigger CI again. Thx.

**Comment by Troublor** [comment]
@klkvr There seems to be some race: the last commit (just some refactoring) is not included in the CI. But the previous CI passes, so everything should look good now.

**Comment by klkvr** [comment]
@Troublor mind updating patch in https://github.com/foundry-rs/foundry/pull/7623? (or creating a new PR if you don't have access to that branch)

**Comment by Troublor** [comment]
@klkvr No problem. I will create a new PR for that.

**Comment by Troublor** [comment]
@klkvr I created another PR to test on foundry: https://github.com/foundry-rs/foundry/pull/8377

Foundry would need a little patch as well for one integration test: `can_extract_config_values`: The expected value of remapping name should have a trailing slash.

Other than this, all tests passes and everything looks good.

**Comment by klkvr** [comment]
@Troublor nice! does this solve the initial issue you had in #47 with compiling contract from Etherscan? If so, I think this is good to merge

**Comment by ZhangZhuoSJTU** [comment]
> @Troublor nice! does this solve the initial issue you had in #47 with compiling contract from Etherscan? If so, I think this is good to merge

I think the original issue is solved after this patch.

**Review by DaniPopes — APPROVED** [review]

**Comment by Troublor** [comment]
@klkvr Yes, problem solved. Thx.
